# Generated by Django 5.0.4 on 2024-04-11 04:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duocgame', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPofile',
            new_name='UserProfile',
        ),
    ]
