# Generated by Django 5.0.4 on 2024-04-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duocgame', '0003_category_game_order_orderitem_order_games_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMINISTRADOR'), ('cliente', 'CLIENTE')], max_length=25),
        ),
    ]
