# Generated by Django 5.0.4 on 2024-04-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duocgame', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('cliente', 'CLIENTE'), ('admin', 'ADMINISTRADOR')], max_length=25),
        ),
    ]
