# Generated by Django 5.0.4 on 2024-04-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duocgame', '0005_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMINISTRADOR'), ('cliente', 'CLIENTE')], max_length=25),
        ),
    ]
