# Generated by Django 5.0.4 on 2024-04-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duocgame', '0007_consola_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consola',
            name='ram',
        ),
        migrations.AlterField(
            model_name='consola',
            name='Storage',
            field=models.CharField(max_length=100),
        ),
    ]
