# Generated by Django 5.0.4 on 2024-04-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duocgame', '0009_rename_storage_consola_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMINISTRADOR'), ('cliente', 'CLIENTE')], max_length=25),
        ),
    ]
